name: PEP8 Check with flake8
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flake8
      - name: Run Flake8
        id: lint
        run: |
          set +e
          result=$(flake8 .)
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $exit_code
        continue-on-error: true
      - name: Send result via dooray alert when lint failure
        if: steps.lint.outputs.exit_code != '0'
        run: |
          echo "🚨 Sending flake8 result..."
          curl -X POST https://nhnent.dooray.com/services/3234962574780345705/4132425382063010358/QicdugUEQ1aLyOidQFZY1Q \
            -H "Content-Type: application/json" \
            -d "{\"botName\":\"Github actions\",\"botIconImage\":\"https://static.dooray.com/static_images/dooray-bot.png\",\"text\":\"${{ steps.lint.outputs.result }}\"}"
