name: PEP8 Check with flake8
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flake8
      - name: Run Flake8
        id: run_flake8
        run: |
          result=$(flake8 .)
          echo "my_output=$result" >> $GITHUB_OUTPUT
      - name: Send dooray alert on failure
        if: failure()
        run: |
          curl -X POST https://nhnent.dooray.com/services/3234962574780345705/4132425382063010358/QicdugUEQ1aLyOidQFZY1Q \
            -H "Content-Type: application/json" \
            -d '{"botName": "Github actions", "botIconImage": "https://static.dooray.com/static_images/dooray-bot.png", "text":"${{ steps.run_flake8.outputs.my_output }}"}'
